### PR TITLE
Project list refresh and startup bug fix

### PR DESCRIPTION
**Pull request by ReDarkTechnology**
I encountered some problems and decided to make a fork of it, this is my first pull request so I hope this contribution isn't breaking much

Anyway here's the stuff that I fixed:
- Adding an editor folder in the settings doesn't refresh the project list (and as the result, the versions are still all red even if the editors are added already)
- On startup, GetElapsedTime vomits an error: System.ArgumentOutOfRangeException: 'The added or subtracted value results in an un-representable DateTime.' which doesn't let me to even start the program in the first place

I remade the whole GetElapsedTime because that is the main bug I wanted to fix, case scenario is when the date time desync or goes backwards, the DateTime it's trying to display is a minus time, when that happened, I made it to just say "Right now"

### CODE REVIEW

**Comment by unitycoder** [comment]
thanks, i'll have a look!

**Comment by unitycoder** [comment]
Update Project list after adding editor looks fine, will add it soon.

For the GetElapsed, i did something similar in Dev branch just recently, it also removes the processDot part,
so if you want to have a look or even test if that works for you:
https://github.com/unitycoder/UnityLauncherPro/commit/227eac3030858633a21bc7cb845d15559c06a3bc
(it includes those plural "s" values too)

**Comment by ReDarkTechnology** [comment]
Tested it, that fix also works too in that specific case!

**Comment by unitycoder** [comment]
Ok good!
i'll close this one and add the project list refresh manually (not smart enough to merge 1 part of this request : )

it will go into dev branch for now, until i merge back & make new build.

**Pull request closed without merging**
