### PR TITLE
Alpha Release Notes: bug fix and code change to match change in website.

### PR DESCRIPTION
**Pull request by SixParQuatre**
all in the title!

### CODE REVIEW

**Comment by unitycoder** [comment]
thanks i'll have a look.

**Comment by unitycoder** [comment]
still thinking about the comment and that while loop..

it would be confusing if "wrong version" notes open,
but also annoying if there would be error messagebox..
https://github.com/unitycoder/UnityLauncherPro/pull/152/commits/196595eef2595695e1cfbcc7d2c20858ba2a0637#diff-b045d7dc0df9dfd6e7d9ecbe44bc4e5d312e040a5c2264dc22d154bf08978548R610

maybe it should just fallback to old release notes (even though alpha notes is enabled),
could display statusbar message about it.. or append something in the url #no_alpha_release_notes_for_this_version something

**Comment by SixParQuatre** [comment]
I don't love it either. I think the better UX would be to have 2 buttons: "Release Notes" and "Cumulated Release Notes".
Releases Notes just shows the individual release notes; and default to the non-alpha version when a non-final version is picked.
Cumulated Release Notes is then disabled if a non-final version is selection; with the tooltip mentioning it only works for final versions.
image

**Comment by unitycoder** [comment]
sorry haven't had time to look into this more yet.. 

still wondering what is the best way to handle it..

one other option:
could disable "release notes" button, if its not available for selected version,
and then enable cumulative button..

**Comment by SixParQuatre** [comment]
No worries! I've actually made the change to have 2 button; I wanted to test it locally for a few day and clean the code up before I submitted a pull request

**Pull request closed without merging**
